In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

In [2]:
from astropy.coordinates import SkyCoord
from hips import *

In [3]:
geometry = WCSGeometry.create(
     skydir=SkyCoord(355, -1, frame='galactic', unit='deg'),
     width=2000, height=1000, fov="2.5 deg",
     coordsys='galactic', projection='AIT',
)

In [4]:
url = 'http://alasky.u-strasbg.fr/DSS/DSSColor/properties'
hips_survey = HipsSurveyProperties.fetch(url)

In [6]:
painter = SimpleTilePainter(geometry, hips_survey, 'jpg')
painter.run()

In [8]:
painter.tiles[0].meta.skycoord_corners.to_pixel(geometry.wcs)

(array([ 1693.36422304,  2062.74575808,  2184.07590764,  1814.27827654]),
 array([ 275.89087349,  313.2544183 ,  -38.01631706,  -75.1228155 ]))

In [12]:
projection = painter.projection(painter.tiles[0])

### Operations on `skimage.transform.ProjectiveTransform` object

In [14]:
projection.params

array([[ -1.41078313e-01,   1.40596467e+00,   3.61575343e+02],
       [ -1.33557026e+00,  -4.61310674e-01,   2.89944950e+03],
       [  2.38893246e-06,  -1.61423513e-06,   9.95560874e-01]])

In [16]:
projection.residuals

<bound method GeometricTransform.residuals of <skimage.transform._geometric.ProjectiveTransform object at 0x7f5a26cd5cc0>>

In [17]:
projection.estimate

<bound method ProjectiveTransform.estimate of <skimage.transform._geometric.ProjectiveTransform object at 0x7f5a26cd5cc0>>

In [18]:
projection.inverse

<bound method ProjectiveTransform.inverse of <skimage.transform._geometric.ProjectiveTransform object at 0x7f5a26cd5cc0>>